### ISSUE TITLE
[Feature Request] Row ordering 

### ISSUE THREAD

**Issue by dillingham** [64robots/nova-row#1]
Ability to change the order of the resulting json by dragging and dropping the rows or with up/down arrows on each row,  Im including some UI inspiration

![interactions](https://user-images.githubusercontent.com/29180903/45374728-f7c48580-b5c0-11e8-9181-8bb2b8aae6e6.png)

**Comment by disitec** [comment]
This package has been merged into https://github.com/64robots/nova-fields. Feel free to reopen this issue there if still happen.
