### ISSUE TITLE
[Feature Request] BelongsTo relationship support

### ISSUE THREAD

**Issue by dillingham** [64robots/nova-row#2]
Ability to include a belongsTo relationship select, searchable, and have it result in a `relation_id` format

**Comment by disitec** [comment]
We are working on this package as we need for our use cases with our clients. This is absolutely planned. Feel free to open a PR or suggest desired API

**Comment by disitec** [comment]
This package has been merged into https://github.com/64robots/nova-fields. Feel free to reopen this issue there if still happen.
