### ISSUE TITLE
Regarding validation

### ISSUE THREAD

**Issue by shirshak55** [64robots/nova-row#5]
is it possible to have validation like at least one row is require or maximum 10 rows.

**Comment by dillingham** [comment]
I haven't tested it, but I wonder also if the individual fields validation gets checked when form submit.

`Row` having a [https://laravel.com/docs/5.7/validation#rule-size](size) validation is cool. 
Or being able to accept the wildcard validation rules

**Comment by disitec** [comment]
This package has been merged into https://github.com/64robots/nova-fields. Feel free to reopen this issue there if still happen.
