### ISSUE TITLE
Setting default classes on form elements

### ISSUE THREAD

**Issue by mdixon18** [64robots/nova-row#6]
This package is great, and works really well with Nova Fields.

When you implement another package say FilemanagerField it would be nice if you could set a default width / toggle off labels so that the fields that you can't call methods on can still be aligned nicely.

To prevent something like the below:

<img width="811" alt="screen shot 2018-09-12 at 16 21 18" src="https://user-images.githubusercontent.com/7197697/45435266-1e112080-b6a8-11e8-87d5-c69eeb986aeb.png">

Something like:

`->defaultFieldClasses('w-full px-8 py-6')->defaultHideLabelInForms()`

**Comment by disitec** [comment]
We are working on this but only for R64 fields. Third party (and core) fields have this classes fixed. We are making this package as much configurable as possible so everybody could use to develop extendable packages
